name: audioplayers
description: A flutter plugin to play multiple audio files simultaneously
version: 0.13.1
author: Luan Nico <luannico27@gmail.com>
homepage: https://github.com/luanpotter/audioplayer

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin
      macos:
        pluginClass: AudioplayersPlugin

dependencies:
  uuid: ^2.0.4
  path_provider: ^1.5.1
  path_provider_macos: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^0.12.0+3
  test: ^1.9.4

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
